export enum ACLTypeEnum {
  MANAGE = 'manage',
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum ModulesTypeEnum {
  ALL = 'all',
  ACADEMIC_YEAR = 'AcademicYear',
  ADMIN = 'Admin',
  ASSIGNMENT = 'Assignment',
  ATTENDANCE = 'Attendance',
  BADGE = 'Badge',
  CAMPUS = 'Campus',
  CCA = 'Cca',
  CCA_YEAR = 'CcaYear',
  CLASS_YEAR = 'ClassYear',
  CLASSROOM = 'Classroom',
  LESSON = 'Lesson',
  LESSON_BUILDER = 'LessonBuilder',
  MATERIAL = 'Material',
  NOTIFICATION = 'Notification',
  PARENT = 'Parent',
  PROGRAMME = 'Programme',
  QUESTION = 'Question',
  SCHEDULE = 'Schedule',
  SOW = 'ScopeOfWork',
  STUDENT = 'Student',
  STUDENT_ANSWER = 'StudentAnswer',
  STUDENT_ASSIGNMENT = 'StudentAssignment',
  STUDENT_BADGE = 'StudentBadge',
  STUDENT_LESSON = 'StudentLesson',
  SUBJECT = 'Subject',
  SUBJECT_YEAR = 'SubjectYear',
  TEACHER = 'Teacher',
  TOPIC = 'Topic',
  USER_ROLE = 'UserRole',
}
